name: AgenticTodoDemo
options:
  bundleIdPrefix: com.agentic-loop
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

targets:
  AgenticTodoDemo:
    type: application
    platform: iOS
    sources:
      - AgenticTodoDemo
    info:
      path: AgenticTodoDemo/Info.plist
      properties:
        CFBundleDisplayName: AgenticTodo
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.agentic-loop.demo
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: "NO"
