name: AgenticTodoDemo
options:
  bundleIdPrefix: com.agentic-loop
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

targets:
  AgenticTodoDemo:
    type: application
    platform: iOS
    sources:
      - AgenticTodoDemo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.agentic-loop.demo
        INFOPLIST_VALUES: >-
          CFBundleDisplayName=AgenticTodo
          CFBundleName=AgenticTodoDemo
          CFBundleShortVersionString=1.0
          CFBundleVersion=1
          UILaunchScreen={}
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: "NO"
